### ISSUE TITLE
Repo should not include .DS_Store files

### ISSUE THREAD

**Issue by anhdat** [MeoBeoI/MangaLover#1]
# Repo should not include .DS_Store files

* Author(s): [Dat Truong](https://github.com/anhdat)
* Status: **Awaiting review**

## Introduction

Since `.DS_Store` files are only valid in Mac OS X and have no meaning on code logic

## Motivation

There're files in repo that serve no purpose on application usage. These files should be ignored.

## Proposed solution

Add an entry of `.DS_Store` to `.gitignore`. Then untrack these `.DS_Store` files

**Comment by MeoBeoI** [comment]
Thank for your reporting, I just added `.gitignore` file in this repos.
