### ISSUE TITLE
Explicitly declare jQuery version

### ISSUE THREAD

**Issue by anhdat** [MeoBeoI/MangaLover#2]
# Explicitly declare jQuery version

* Author(s): [Dat Truong](https://github.com/anhdat)
* Status: **Awaiting review**

## Introduction

One problem about inejected code that use jQuery is that the injecting website
may have already used jQuery themselves, and maybe with different version. jQuery
files inside extension should have a clear version.

## Motivation

Other than reasonable when manage multi jQuery versions on a same website, some methods
may already obsoleted in one version and not available in another, therefore, logic code
should also reflects multiple version of jQuery support.

## Proposed solution

Change file name of injected jQuery files in both file name and manifest file.

**Comment by MeoBeoI** [comment]
I've changed jquery file name, used `noConfict` mode of Jquery, and `closure` to make sure everything won't conflict in the future
